spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username:
    password:
  jpa:
    hibernate:
      # TODO: reconsider this setting before finishing development
      ddl-auto: update
    show-sql: true